apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

images:
- name: nginx
  newName: sandesh12055/san-nginx-app
  newTag: f17430de9e8e4a7bfac878484c27326e7aaa75a9

# Example patch: QA usually needs more replicas than Dev
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: my-app
