apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

images:
- name: nginx
  newName: sandesh12055/san-nginx-app
  newTag: 951b3419128ad63b3d0163fc51cd41a92d079e02
