apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qalamsal/my-k8s-repo
    targetRevision: HEAD
    path: overlays/qa
  destination:
    server: https://172.18.0.5:6443
    namespace: ns-qa-env
  syncPolicy:
    automated: null  # Manual Sync for promotion
    syncOptions:
    - CreateNamespace=true
EOF