apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# This adds 'qa-' to the beginning of all resource names (e.g., qa-my-app)
namePrefix: qa-

# This is where you 'Promote' by using a different image tag than Dev
images:
  - name: nginx
    newTag: "1.23.1"

# Example patch: QA usually needs more replicas than Dev
patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5