#  only udpate dev pipeline
name: Update Dev Overlay
on:
  workflow_dispatch: # This creates the manual button in GitHub UI
        
  pull_request:
    branches: [main]
    types: [closed]

# Define image name using GHCR format
env:
    DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/san-nginx-app

jobs:
  dev-sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: dev #env on git
    permissions:
        contents: write   # To push Kustomize changes
        packages: write   # To push the Docker image to GHCR
    
    steps:
      - name: Checkout Github Code Base
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
              # Create short SHA
              SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
              TAG="${{ env.DOCKER_REPO }}:$SHORT_SHA"
              
              #Test the path
              ls -la
              
              echo "Building $TAG..."
              docker build -t $TAG .
              docker push $TAG
              
              # Store for next step
              echo "FULL_IMAGE_TAG=$TAG" >> $GITHUB_ENV
              echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
    
      - name: Update Dev Tag
        run: |
            cd overlays/dev
            # Update Kustomize with the NEWLY PUSHED image
            kustomize edit set image nginx=${{ env.FULL_IMAGE_TAG }}
        
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: bump dev to ${{ env.SHORT_SHA }}"
            git push origin main