#  only udpate dev pipeline
name: Update Dev Overlay
on:
  workflow_dispatch: # This creates the manual button in GitHub UI
        
  pull_request:
    branches: [main]
    types: [closed]

# Define image name using GHCR format
env:
    DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/san-nginx-app

jobs:
  dev-sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: dev #env on git
    permissions:
        contents: write   # To push Kustomize changes    
    steps:
      - name: Checkout Github Code Base
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 2. NEW: Build and push the image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Replace 'your-dockerhub-username' with your actual username
          # Replace 'your-repo-name' with your Docker Hub repository name
          tags: |
            sandesh12055/san-nginx-app:latest
            sandesh12055/san-nginx-app:${{ github.sha }}

      # 3. Update Kustomize (This now points to the image you just pushed)
      - name: Update Dev Tag
        run: |
          cd overlays/dev
          SHORT_SHA=${GITHUB_SHA:0:7}
          # Update the kustomize image to match the one pushed above
          kustomize edit set image nginx=sandesh12055/san-nginx-app:$SHORT_SHA
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deploy(dev): bump image to $SHORT_SHA [skip ci]"
          git push origin main